app/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users

  resource :groups

end

app/app/models/group.rb
class Group < ActiveRecord::Base
end

app/app/models/user.rb
class User < ActiveRecord::Base
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def respond(action_name = nil, controller_name = nil)
    if action_name.nil?
      action_name = params[:action_name]
    end
    if controller_name.nil?
      controller_name = params[:controller_name]
    end

    if request.xhr?
      render "/#{controller_name}/#{action_name}.js.erb"
    else
      render "/#{controller_name}/#{action_name}.html.haml"
    end

  end

end

app/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new]
  def index
  end

  def new
    @user = User.new
    respond
  end

  def create
  end

  def show
  end

  def destroy
  end

  def update
  end

  def edit
  end

  private
  def set_all_users
    @users = User.all
  end
  def set_user
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e

    end
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
  def icon(icon)
    content = content_tag :i, icon, class: 'material-icons'
    content.html_safe
  end
end

app/app/helpers/groups_helper.rb
module GroupsHelper
end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/home/index.html.haml
I have a dream!

app/app/views/layouts/_navigation.html.haml
.navigation_wrapper
  .navigation
    %ul
      %li=link_to icon('home')+ ' Home', root_path
      %li=link_to icon('people') + ' Users', users_path
      %li=link_to icon('group_work') + ' Groups', groups_path

app/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = csrf_meta_tags
    %title Spire

  %body
    .header_wrapper
      .header
        = render partial: '/layouts/navigation'
    .content_wrapper
      .content
        = yield

app/app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

app/app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml

app/app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml